apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-du-monitoring-cronjob
data:
  cronjob: |
    ### cron file for running the export script
    # TODO: find a better way to configure the schedule (helm values?)
    0-59/5 * * * * root sh /scripts/export-influxdb-database-size.sh ## run the export script at every 5th minute from 0 through 59 (one minute ahead of metric retention defined in influxdb-metrics-retention/cronjob.yaml)
    # An empty line is required at the end of this file for a valid cron file.