apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: influxdb-du-monitoring-service-monitor
    namespace: monitoring
    labels:
        app: prometheus-operator-influxdb-du-monitoring
        release: prometheus-operator
spec:
    selector:
        matchLabels:
            app: influxdb-du-monitoring
    namespaceSelector:
        matchNames:
        - influxdb-prometheus
    endpoints:
    - port: web
      path: /metrics