apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: influxdb-metrics-retention-cronjob
  labels:
    app: influxdb-metrics-retention
spec:
  schedule: "1-59/5 * * * *" # At every 5th minute from 1 through 59 (one minute after du monitoring defined in influxdb/cronjob-cm.yaml)
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: influxdb-metrics-retention
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: python-script
              configMap:
                name: influxdb-metrics-retention-script
          containers:
            - name: influxdb-metrics-retention
              image: elastisys/influxdb-metrics-retention:latest
              command: ["python3", "/app/influxdb_size_based_metrics_retention.py"]
              env:
              - name: INFLUXDB_HOST
                value: influxdb
              - name: INFLUXDB_PORT
                value: "8086"
              - name: INFLUXDB_USER
                valueFrom:
                  secretKeyRef:
                    name: influxdb-auth
                    key: INFLUXDB_USER
              - name: INFLUXDB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: influxdb-auth
                    key: INFLUXDB_PWD
              - name: INFLUXDB_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: common-env-vars-cm
                    key: influxdb-retention-database
              - name: INFLUXDB_MIN_SHARDS
                value: "1"
              - name: INFLUXDB_DATABASE_SIZE_LIMIT
                value: "5000000"
              - name: PROMETHEUS_HOST
                value: prometheus-operator-prometheus.monitoring
              - name: PROMETHEUS_PORT
                value: "9090"
              - name: PROMETHEUS_INFLUXDB_METRIC
                valueFrom:
                  configMapKeyRef:
                    name: common-env-vars-cm
                    key: prometheus-influxdb-retention-metric-name
              - name: LOGLEVEL
                value: "INFO"
              volumeMounts:
                - name: python-script
                  mountPath: /app
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi
                limits:
                  cpu: 250m
                  memory: 500Mi            