apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: influxdb-backup
  labels:
    app: influxdb-backup
spec:
  # TODO: find a better way to configure the schedule (helm values?)
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: influxdb-backup
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: backups
            emptyDir: {}
          initContainers:
          - name: influxdb-backup
            image: influxdb:1.7.6-alpine
            volumeMounts:
            - name: backups
              mountPath: /backups
            command:
            - /bin/sh
            args:
            - '-c'
            - |
              influxd backup -host $(INFLUX_ADDR) -portable /backups/backup_$(date +%Y%m%d_%H%M%S)
            env:
            - name: INFLUX_ADDR
              valueFrom:
                configMapKeyRef:
                  name: influx-env-cm
                  key: INFLUX_ADDR
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 250m
                memory: 500Mi
          containers:
          - name: aws-cli-util
            image: atlassian/pipelines-awscli:1.16.185
            command:
            - /bin/sh
            args:
            - '-c'
            - |
              printenv
              aws s3 --endpoint-url $(S3_REGION_ENDPOINT) sync /backups s3://$(S3_INFLUX_BUCKET_NAME) --acl "private"
            env:
            # Aws s3 cli variables.
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: influx-env-cm
                  key: S3_REGION
            - name: S3_REGION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: influx-env-cm
                  key: S3_REGION_ENDPOINT
            - name: S3_INFLUX_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: influx-env-cm
                  key: S3_INFLUX_BUCKET_NAME
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: influx-backup-secret
                  key: S3_SECRET_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: influx-backup-secret
                  key: S3_ACCESS_KEY
            volumeMounts:
            - name: backups
              mountPath: /backups
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 250m
                memory: 300Mi
